# Generated by Django 5.0.6 on 2024-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='teams', to='leagues.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bye_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='leagues',
            field=models.ManyToManyField(blank=True, to='leagues.league'),
        ),
    ]
